In [1]:
import numpy as np
np.__version__

'1.21.5'

# CREATE 1d ARRAY USING ARRAY FUNCTION

In [2]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
print(a.dtype)
print(a.shape)

[1 2 3 4 5]
int32
(5,)


# Create 1d array using arange function

In [3]:
arr =np.arange(10)
arr
print(arr.dtype)
print(arr.shape)

int32
(10,)


# CREATE A 2D ARRAY USING ARRAY

In [4]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.dtype)
print(b.shape)

[[1 2 3]
 [4 5 6]]
int32
(2, 3)


# CREATE 2d ARRAY USING ARANGE FUNCTION

In [5]:
b = np.arange(12).reshape(6,2)
print(b)
print(b.dtype)
print(b.shape)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
int32
(6, 2)


# CREATE 3D ARRAY USING ARRAY FUNCTION

In [6]:
b = np.array(
[
    [[1,2,3],[3,2,1]],
    [[4,5,6],[6,5,4]],
    [[7,8,9],[9,8,6]]
]
)
print(b)
print(b.dtype)
print(b.shape)

[[[1 2 3]
  [3 2 1]]

 [[4 5 6]
  [6 5 4]]

 [[7 8 9]
  [9 8 6]]]
int32
(3, 2, 3)


# CREATE 3D ARRAY USING ARANGE FUNCTION

In [7]:
b =np.arange(18).reshape(3,2,3)
print(b)
print(b.dtype)
print(b.shape)
print(b.size)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
int32
(3, 2, 3)
18


# CREATE ARRAY USING ZEROS

In [8]:
b = np.zeros(10).reshape(2,5)
print(b)
print(b.dtype)
print(b.shape)
print(b.size)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
float64
(2, 5)
10


# CREATE ARRAY USING ONES

In [9]:
b = np.ones(6).reshape(2,3)
print(b)
print(b.dtype)
print(b.shape)
print(b.size)

[[1. 1. 1.]
 [1. 1. 1.]]
float64
(2, 3)
6


# CREATE ONES USING 2D ARRAY


In [10]:
b = np.ones((6,2),dtype=np.int32)
print(b)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


# CREATE ARRAY OF ONES USING 3D

In [11]:
b = np.ones((6,3,2),dtype=np.int32)
print(b)
print(b.dtype)
print(b.shape)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]
int32
(6, 3, 2)


# CREATE AN ARRAY WITH RANDOM NUMBERS USING 1d ARRAY

In [12]:
b =np.random.randint(1,5,size=(5))
print(b)
print(b.dtype)
print(b.shape)

[1 1 1 1 4]
int32
(5,)


# CREATE AN ARRAY USING RANDOM NUMBERS USING 2D ARRAY 

In [13]:
b =np.random.randint(2,7,size=(3,3))
print(b)
print(b.dtype)
print(b.shape)

[[2 3 5]
 [3 5 2]
 [4 4 6]]
int32
(3, 3)


# CREATE AN ARRAY WITH RANDOM NUMBERS USING 3D ARRAY

In [14]:
b =np.random.randint(10,20,size=(3,3,3))
print(b)
print(b.dtype)
print(b.shape)

[[[18 16 13]
  [10 18 17]
  [11 19 10]]

 [[15 13 19]
  [17 16 10]
  [19 18 13]]

 [[12 13 19]
  [11 19 13]
  [12 18 14]]]
int32
(3, 3, 3)


# CREATE ARRAY WITH SINGLE LOW MULTIPLE HIGH

In [15]:
a = np.random.randint(5,[10,20,30])
print(a)
print(a.dtype)
print(a.shape)

[ 6 17 14]
int32
(3,)


# CREATE ARRAY WITH MUTIPLE LOW SINGLE HIGH

In [16]:
a = np.random.randint([4,5,6],7)
print(a)
print(a.dtype)
print(a.shape)

[6 6 6]
int32
(3,)


# CREATE ARRAY WITH MUTILPLE HIGH AND MULTIPLE LOW

In [17]:
a = np.random.randint([1,2,3],[10,20,30],size=(3,1,3))
print(a)
print(a.dtype)
print(a.shape)

[[[ 9 10 23]]

 [[ 1 18  3]]

 [[ 8  9 20]]]
int32
(3, 1, 3)


# RANDOM RANDN FUNCTION 1D

In [18]:
import numpy as np
a = np.random.randn(3)
print(a)
print(a.dtype)
print(a.shape)

[-0.054826    1.28812452  1.84824705]
float64
(3,)


# RANDOM RANDN FUNCTION 2D

In [19]:
a = np.random.randn(3,3)
print(a)
print(a.dtype)
print(a.shape)

[[ 2.42107381  0.13962352 -0.30768067]
 [-0.90457765  0.17647693  0.00866513]
 [ 1.17950696  0.17176851 -0.29071138]]
float64
(3, 3)


# RANDOM RANDN FUNCTION 3D

In [20]:
a = np.random.randn(3,2,3)
print(a)
print(a.dtype)
print(a.shape)

[[[ 0.05491357  0.65665457 -0.72629386]
  [-0.80004804 -0.12928978 -0.71829986]]

 [[ 1.58989157  1.77767199  3.48686172]
  [ 0.53792122 -0.51783385 -0.2737105 ]]

 [[ 0.54459645  0.05254813  0.23799473]
  [-1.46512028 -0.67116733  0.78485206]]]
float64
(3, 2, 3)


# CREATE RANDOM RAND FUNCTION

In [21]:
a = np.random.rand(10)
print(a)
print(a.dtype)
print(a.shape)

[0.42898188 0.89483144 0.72429749 0.90741696 0.66197282 0.85761704
 0.49736638 0.96070436 0.99577162 0.46444079]
float64
(10,)


# POSITIVE INDEXING IN ARRAY 

In [22]:
#array with 1D
arr=([2,3,4,5,6,7,8])
print(arr[0])

2


In [23]:
#array with 2D
arr=np.array([[1,2,3],[4,5,6]])
print(arr[1,1])

5


In [24]:
#array with 3D
arr=np.array(
[
    [[1,2,3],[3,2,1]],
    [[4,5,6],[6,5,4]],
    [[7,8,9],[9,8,7]]
]
)
print(arr[2,1,0])
print(arr[1,0,2])

9
6


In [25]:
#negative array indexing 1D
arr=np.array([1,2,3,4,5])
print(arr[-3])

3


In [26]:
#negative array indexing 2D
arr=np.array([[1,2,3],[4,5,6]])
print(arr[-1,-2])

5


In [27]:
#negative array indexing 3D
arr=np.array(
[
    [[1,2,3],[3,2,1]],
    [[4,5,6],[6,5,4]],
    [[7,8,9],[9,8,7]]
]
)
print(arr[-1,-2,-2])
print(arr[-2,-2,-2])
print(arr[-3,-1,-3])

8
5
3


# NUMPY ARRAY SLICING

In [28]:
import numpy as np
arr =np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [29]:
arr =np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [30]:
arr =np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


# NEGATIVE SILCING

In [31]:
arr =np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [32]:
arr =np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [33]:
arr =np.array([1,2,3,4,5,6,7])
print(arr[::3])

[1 4 7]


# SLICING 2D ARRAY

In [34]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])
print(arr[0,2:3])

[7 8 9]
[3]


In [35]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [36]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


# NumPy Array Copy vs view

In [37]:
import numpy as np
arr=np.array([1,2,3,4,5])
a=np.copy(arr)
arr[2]=6
a[4]=3
print(arr)
print(a)

[1 2 6 4 5]
[1 2 3 4 3]


In [38]:
import numpy as np 

arr=np.array([1,2,3,4,5])
x=arr.view()
arr[2]=6

print(arr)
print(x)

[1 2 6 4 5]
[1 2 6 4 5]


# Reshape()Function

In [39]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("original array")
print(arr)
#2darray
a1=arr.reshape(5,2)
print("\n2d array (5,2)")
print(a1)
a2=arr.reshape(2,5)
print(a2)
#3d array
a3=arr.reshape(2,1,5)
print("\n3d array (2,1,5)")
print(a3)


original array
[ 1  2  3  4  5  6  7  8  9 10]

2d array (5,2)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

3d array (2,1,5)
[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]]


# Sum()Function

In [40]:
arr =np.array([1,2,3,4,5])
print("original array")
print(arr)
print(np.sum(arr))
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("\n 2d array")
print(a)
print(np.sum(a))
a1=np.array(
[
    [[1,2,3],[4,5,6]],
    [[7,8,9],[1,2,3]],
    [[4,5,6],[7,8,9]]
]
)
print("\n 3d array")
print(a1)
print(np.sum(a1))

original array
[1 2 3 4 5]
15

 2d array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
55

 3d array
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]

 [[4 5 6]
  [7 8 9]]]
90


In [41]:
arr=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print("original array")
print(arr)
print("\n sum axis 0") # acros column (column wise)
print(np.sum(arr,axis=0))
print("\n sum axis 1") # across row (row wise)
print(np.sum(arr,axis=1))

original array
[[1 2 3 4 5]
 [2 3 4 5 6]]

 sum axis 0
[ 3  5  7  9 11]

 sum axis 1
[15 20]


# Mean()Function

In [42]:
arr=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(np.mean(arr))

3.5


In [43]:
arr=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print("original array")
print(arr)
print("\n mean axis 0") # acros column (column wise)
print(np.mean(arr,axis=0))
print("\n mean axis 1") # across row (row wise)
print(np.mean(arr,axis=1))

original array
[[1 2 3 4 5]
 [2 3 4 5 6]]

 mean axis 0
[1.5 2.5 3.5 4.5 5.5]

 mean axis 1
[3. 4.]


# Std() Function

In [48]:
a=np.array([[1,2,3],[4,5,6]])
print(np.std(a))
print(np.std(a,axis=0))
print(np.std(a,axis=1))

1.707825127659933
[1.5 1.5 1.5]
[0.81649658 0.81649658]


# var()function

In [50]:
a=np.array([[1,2,3],[4,5,6]])
print(np.var(a))
print(np.var(a,axis=0))
print(np.var(a,axis=1))

2.9166666666666665
[2.25 2.25 2.25]
[0.66666667 0.66666667]


# MIN

In [51]:
a=np.array([[1,2,3],[4,5,6]])
print(np.min(a))
print(np.min(a,axis=0))
print(np.min(a,axis=1))

1
[1 2 3]
[1 4]


# max

In [52]:
a=np.array([[1,2,3],[4,5,6]])
print(np.max(a))
print(np.max(a,axis=0))
print(np.max(a,axis=1))

6
[4 5 6]
[3 6]
