In [1]:
import numpy as np
np.__version__

'1.21.5'

# CREATE 1d ARRAY USING ARRAY FUNCTION

In [2]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
print(a.dtype)
print(a.shape)

[1 2 3 4 5]
int32
(5,)


# Create 1d array using arange function

In [3]:
arr =np.arange(10)
arr
print(arr.dtype)
print(arr.shape)

int32
(10,)


# CREATE A 2D ARRAY USING ARRAY

In [4]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.dtype)
print(b.shape)

[[1 2 3]
 [4 5 6]]
int32
(2, 3)


# CREATE 2d ARRAY USING ARANGE FUNCTION

In [5]:
b = np.arange(12).reshape(6,2)
print(b)
print(b.dtype)
print(b.shape)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
int32
(6, 2)


# CREATE 3D ARRAY USING ARRAY FUNCTION

In [6]:
b = np.array(
[
    [[1,2,3],[3,2,1]],
    [[4,5,6],[6,5,4]],
    [[7,8,9],[9,8,6]]
]
)
print(b)
print(b.dtype)
print(b.shape)

[[[1 2 3]
  [3 2 1]]

 [[4 5 6]
  [6 5 4]]

 [[7 8 9]
  [9 8 6]]]
int32
(3, 2, 3)


# CREATE 3D ARRAY USING ARANGE FUNCTION

In [7]:
b =np.arange(18).reshape(3,2,3)
print(b)
print(b.dtype)
print(b.shape)
print(b.size)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
int32
(3, 2, 3)
18


# CREATE ARRAY USING ZEROS

In [8]:
b = np.zeros(10).reshape(2,5)
print(b)
print(b.dtype)
print(b.shape)
print(b.size)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
float64
(2, 5)
10


# CREATE ARRAY USING ONES

In [9]:
b = np.ones(6).reshape(2,3)
print(b)
print(b.dtype)
print(b.shape)
print(b.size)

[[1. 1. 1.]
 [1. 1. 1.]]
float64
(2, 3)
6


# CREATE ONES USING 2D ARRAY


In [10]:
b = np.ones((6,2),dtype=np.int32)
print(b)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


# CREATE ARRAY OF ONES USING 3D

In [11]:
b = np.ones((6,3,2),dtype=np.int32)
print(b)
print(b.dtype)
print(b.shape)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]
int32
(6, 3, 2)


# CREATE AN ARRAY WITH RANDOM NUMBERS USING 1d ARRAY

In [12]:
b =np.random.randint(1,5,size=(5))
print(b)
print(b.dtype)
print(b.shape)

[3 3 1 1 3]
int32
(5,)


# CREATE AN ARRAY USING RANDOM NUMBERS USING 2D ARRAY 

In [13]:
b =np.random.randint(2,7,size=(3,3))
print(b)
print(b.dtype)
print(b.shape)

[[6 6 5]
 [6 5 6]
 [6 2 3]]
int32
(3, 3)


# CREATE AN ARRAY WITH RANDOM NUMBERS USING 3D ARRAY

In [14]:
b =np.random.randint(10,20,size=(3,3,3))
print(b)
print(b.dtype)
print(b.shape)

[[[12 19 11]
  [13 12 12]
  [18 18 13]]

 [[13 17 13]
  [17 12 18]
  [16 19 10]]

 [[15 13 11]
  [11 11 19]
  [15 15 17]]]
int32
(3, 3, 3)


# CREATE ARRAY WITH SINGLE LOW MULTIPLE HIGH

In [15]:
a = np.random.randint(5,[10,20,30])
print(a)
print(a.dtype)
print(a.shape)

[ 9 10  6]
int32
(3,)


# CREATE ARRAY WITH MUTIPLE LOW SINGLE HIGH

In [16]:
a = np.random.randint([4,5,6],7)
print(a)
print(a.dtype)
print(a.shape)

[6 5 6]
int32
(3,)


# CREATE ARRAY WITH MUTILPLE HIGH AND MULTIPLE LOW

In [17]:
a = np.random.randint([1,2,3],[10,20,30],size=(3,1,3))
print(a)
print(a.dtype)
print(a.shape)

[[[ 6  8 24]]

 [[ 4  2 11]]

 [[ 7 19 13]]]
int32
(3, 1, 3)


# RANDOM RANDN FUNCTION 1D

In [18]:
import numpy as np
a = np.random.randn(3)
print(a)
print(a.dtype)
print(a.shape)

[-1.34845412 -1.14366949 -0.17096157]
float64
(3,)


# RANDOM RANDN FUNCTION 2D

In [19]:
a = np.random.randn(3,3)
print(a)
print(a.dtype)
print(a.shape)

[[ 0.14435216  0.23583281 -0.09607392]
 [ 1.07450658 -0.29563849  0.77459477]
 [-0.22821147  1.27693753 -0.66127571]]
float64
(3, 3)


# RANDOM RANDN FUNCTION 3D

In [20]:
a = np.random.randn(3,2,3)
print(a)
print(a.dtype)
print(a.shape)

[[[-0.32147668  0.4771956   0.52539507]
  [-0.2790901   1.22787461 -0.42308033]]

 [[-0.82468041 -1.33915697 -0.11568361]
  [-0.34690879  0.47120627  0.33984798]]

 [[-1.40240842 -0.05086255 -0.18256652]
  [-0.28891615  0.03908182  0.3075509 ]]]
float64
(3, 2, 3)


# CREATE RANDOM RAND FUNCTION

In [22]:
a = np.random.rand(10)
print(a)
print(a.dtype)
print(a.shape)

[0.23393756 0.96146993 0.88657477 0.50069268 0.53110144 0.31655783
 0.09954087 0.89737834 0.34470635 0.16440314]
float64
(10,)


# POSITIVE INDEXING IN ARRAY 

In [30]:
#array with 1D
arr=([2,3,4,5,6,7,8])
print(arr[0])

2


In [33]:
#array with 2D
arr=np.array([[1,2,3],[4,5,6]])
print(arr[1,1])

5


In [35]:
#array with 3D
arr=np.array(
[
    [[1,2,3],[3,2,1]],
    [[4,5,6],[6,5,4]],
    [[7,8,9],[9,8,7]]
]
)
print(arr[2,1,0])
print(arr[1,0,2])

9
6


In [37]:
#negative array indexing 1D
arr=np.array([1,2,3,4,5])
print(arr[-3])

3


In [40]:
#negative array indexing 2D
arr=np.array([[1,2,3],[4,5,6]])
print(arr[-1,-2])

5


In [44]:
#negative array indexing 3D
arr=np.array(
[
    [[1,2,3],[3,2,1]],
    [[4,5,6],[6,5,4]],
    [[7,8,9],[9,8,7]]
]
)
print(arr[-1,-2,-2])
print(arr[-2,-2,-2])
print(arr[-3,-1,-3])

8
5
3


# NUMPY ARRAY SLICING

In [4]:
import numpy as np
arr =np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [5]:
arr =np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [7]:
arr =np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


# NEGATIVE SILCING

In [8]:
arr =np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [15]:
arr =np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [17]:
arr =np.array([1,2,3,4,5,6,7])
print(arr[::3])

[1 4 7]


# SLICING 2D ARRAY

In [21]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])
print(arr[0,2:3])

[7 8 9]
[3]


In [18]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [19]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]
