In [1]:
import numpy as np
np.__version__

'1.21.5'

# CREATE 1d ARRAY USING ARRAY FUNCTION

In [2]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
print(a.dtype)
print(a.shape)

[1 2 3 4 5]
int32
(5,)


# Create 1d array using arange function

In [3]:
arr =np.arange(10)
arr
print(arr.dtype)
print(arr.shape)

int32
(10,)


# CREATE A 2D ARRAY USING ARRAY

In [4]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.dtype)
print(b.shape)

[[1 2 3]
 [4 5 6]]
int32
(2, 3)


# CREATE 2d ARRAY USING ARANGE FUNCTION

In [5]:
b = np.arange(12).reshape(6,2)
print(b)
print(b.dtype)
print(b.shape)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
int32
(6, 2)


# CREATE 3D ARRAY USING ARRAY FUNCTION

In [6]:
b = np.array(
[
    [[1,2,3],[3,2,1]],
    [[4,5,6],[6,5,4]],
    [[7,8,9],[9,8,6]]
]
)
print(b)
print(b.dtype)
print(b.shape)

[[[1 2 3]
  [3 2 1]]

 [[4 5 6]
  [6 5 4]]

 [[7 8 9]
  [9 8 6]]]
int32
(3, 2, 3)


# CREATE 3D ARRAY USING ARANGE FUNCTION

In [7]:
b =np.arange(18).reshape(3,2,3)
print(b)
print(b.dtype)
print(b.shape)
print(b.size)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
int32
(3, 2, 3)
18


# CREATE ARRAY USING ZEROS

In [8]:
b = np.zeros(10).reshape(2,5)
print(b)
print(b.dtype)
print(b.shape)
print(b.size)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
float64
(2, 5)
10


# CREATE ARRAY USING ONES

In [9]:
b = np.ones(6).reshape(2,3)
print(b)
print(b.dtype)
print(b.shape)
print(b.size)

[[1. 1. 1.]
 [1. 1. 1.]]
float64
(2, 3)
6


# CREATE ONES USING 2D ARRAY


In [10]:
b = np.ones((6,2),dtype=np.int32)
print(b)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


# CREATE ARRAY OF ONES USING 3D

In [11]:
b = np.ones((6,3,2),dtype=np.int32)
print(b)
print(b.dtype)
print(b.shape)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]
int32
(6, 3, 2)
