In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('dataset/titanic.csv')
df

PassengerId  Survived  Pclass  \
0              1       0.0       3   
1              2       NaN       1   
2              3       NaN       3   
3              4       NaN       1   
4              5       0.0       3   
..           ...       ...     ...   
886          887       0.0       2   
887          888       1.0       1   
888          889       0.0       3   
889          890       1.0       1   
890          891       0.0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female   NaN      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282      NaN   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     887 non-null    float64
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          713 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         888 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(3), int64(4), object(5)
memory usage: 83.7+ KB


In [5]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  887.000000  891.000000  713.000000  891.000000   
mean    446.000000    0.382187    2.308642   29.704306    0.523008   
std     257.353842    0.486196    0.836071   14.536033    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.000000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  888.000000  
mean     0.381594   32.282530  
std      0.806057   49.758986  
min      0.000000    0.000000  
25%      0.000000    7.917700  
50%      0.000000   14.456250  
75%      0.000000   31.068750  
max      6.000000  512.329200

In [6]:
df.isnull().sum()

PassengerId      0
Survived         4
Pclass           0
Name             0
Sex              0
Age            178
SibSp            0
Parch            0
Ticket           0
Fare             3
Cabin          687
Embarked         2
dtype: int64

In [7]:
df.drop(['PassengerId','Ticket','Fare','Cabin','Name'],inplace=True,axis=1)

In [8]:
df

Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0         0.0       3    male  22.0      1      0        S
1         NaN       1  female  38.0      1      0        C
2         NaN       3  female   NaN      0      0        S
3         NaN       1  female  35.0      1      0        S
4         0.0       3    male  35.0      0      0        S
..        ...     ...     ...   ...    ...    ...      ...
886       0.0       2    male  27.0      0      0        S
887       1.0       1  female  19.0      0      0        S
888       0.0       3  female   NaN      1      2        S
889       1.0       1    male  26.0      0      0        C
890       0.0       3    male  32.0      0      0        Q

[891 rows x 7 columns]

In [9]:
df['Survived'].fillna(method='ffill',inplace=True)
df['Age'].fillna(method='ffill',inplace=True)
df['Embarked'].fillna(method='ffill',inplace=True)




In [10]:
x=df.iloc[:,1:]
x

Pclass     Sex   Age  SibSp  Parch Embarked
0         3    male  22.0      1      0        S
1         1  female  38.0      1      0        C
2         3  female  38.0      0      0        S
3         1  female  35.0      1      0        S
4         3    male  35.0      0      0        S
..      ...     ...   ...    ...    ...      ...
886       2    male  27.0      0      0        S
887       1  female  19.0      0      0        S
888       3  female  19.0      1      2        S
889       1    male  26.0      0      0        C
890       3    male  32.0      0      0        Q

[891 rows x 6 columns]

In [11]:
y=df.iloc[:,-1]
y

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

In [12]:
df['Survived'].isnull().sum()

0

In [13]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
tr = ColumnTransformer(transformers=[
    ('t1',SimpleImputer(),['Age']),
    ('t2',OneHotEncoder(drop='first',sparse=False),['Sex','Embarked'])
] , remainder='passthrough')

In [26]:
x1=tr.fit_transform(x)
x1

array([[22.,  1.,  0., ...,  3.,  1.,  0.],
       [38.,  0.,  0., ...,  1.,  1.,  0.],
       [38.,  0.,  0., ...,  3.,  0.,  0.],
       ...,
       [19.,  0.,  0., ...,  3.,  1.,  2.],
       [26.,  1.,  0., ...,  1.,  0.,  0.],
       [32.,  1.,  1., ...,  3.,  0.,  0.]])

In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x2,y,train_size=0.2)

In [28]:
x_train

array([[22.  ,  1.  ,  0.  , ...,  3.  ,  0.  ,  0.  ],
       [ 0.75,  0.  ,  0.  , ...,  3.  ,  2.  ,  1.  ],
       [13.  ,  0.  ,  0.  , ...,  3.  ,  0.  ,  0.  ],
       ...,
       [26.  ,  1.  ,  0.  , ...,  3.  ,  0.  ,  0.  ],
       [24.  ,  1.  ,  0.  , ...,  3.  ,  0.  ,  0.  ],
       [30.  ,  1.  ,  0.  , ...,  1.  ,  0.  ,  0.  ]])

In [29]:
x_test

array([[50.,  0.,  0., ...,  2.,  0.,  1.],
       [30.,  1.,  0., ...,  3.,  0.,  0.],
       [49.,  1.,  0., ...,  1.,  1.,  1.],
       ...,
       [39.,  1.,  0., ...,  2.,  0.,  0.],
       [24.,  1.,  0., ...,  1.,  0.,  0.],
       [27.,  0.,  0., ...,  2.,  0.,  0.]])

In [30]:

y_train

521    S
469    C
780    C
537    C
675    S
      ..
330    Q
534    S
162    S
499    S
452    C
Name: Embarked, Length: 178, dtype: object

In [31]:
y_test

259    S
538    S
698    C
176    S
834    S
      ..
350    S
607    S
705    S
139    C
717    S
Name: Embarked, Length: 713, dtype: object

In [32]:
from sklearn.tree import DecisionTreeClassifier

In [33]:
dtc=DecisionTreeClassifier()

In [34]:
dtc

DecisionTreeClassifier()

In [35]:
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [36]:
y_pred=dtc.predict(x_test)


In [38]:
y_pred

array(['S', 'S', 'C', 'S', 'S', 'S', 'C', 'C', 'S', 'S', 'S', 'S', 'C',
       'Q', 'Q', 'S', 'S', 'S', 'S', 'S', 'S', 'C', 'S', 'S', 'S', 'C',
       'S', 'S', 'S', 'S', 'S', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'C',
       'S', 'S', 'S', 'C', 'S', 'S', 'S', 'Q', 'S', 'S', 'C', 'S', 'C',
       'C', 'S', 'S', 'S', 'C', 'S', 'S', 'C', 'Q', 'S', 'C', 'S', 'S',
       'S', 'S', 'Q', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'Q', 'S', 'C',
       'C', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
       'Q', 'S', 'S', 'C', 'Q', 'S', 'S', 'C', 'S', 'S', 'S', 'S', 'S',
       'Q', 'S', 'S', 'S', 'Q', 'S', 'Q', 'S', 'C', 'S', 'S', 'S', 'S',
       'S', 'C', 'S', 'S', 'C', 'S', 'S', 'S', 'C', 'S', 'S', 'S', 'C',
       'S', 'Q', 'S', 'S', 'S', 'C', 'C', 'S', 'S', 'S', 'Q', 'S', 'S',
       'S', 'C', 'C', 'S', 'S', 'S', 'S', 'S', 'C', 'Q', 'S', 'S', 'C',
       'S', 'C', 'C', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'C', 'C', 'S',
       'C', 'S', 'S', 'S', 'S', 'Q', 'S', 'C', 'Q', 'S', 'S', 'S